services:
  backend:
    build:
      command: "mvn -B clean package -DskipTests"
    deploy:
      # Für Konsistenz mit Railway.toml laufen wir im Run-Modus statt Jar
      startCommand: "mvn -q spring-boot:run"
      healthcheckPath: "/actuator/health"
      envVars:
        BACKEND_PORT: "8080"
  frontend:
    build:
      command: "npm ci && npm run build"
    deploy:
      startCommand: "npm run preview -- --host 0.0.0.0 --port ${FRONTEND_PORT:-5173}"
      envVars:
        FRONTEND_PORT: "5173"
