name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Maven Verify
        run: mvn -B -DskipITs=false verify

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Frontend
        run: |
          if [ -f package.json ]; then npm ci; fi

      - name: Frontend Tests
        run: |
          if [ -f package.json ]; then npm test -- --ci; fi

      - name: Markdown Lint
        run: |
          if [ -f package.json ]; then npx markdownlint 'docs/**/*.md' || true; fi
